version: '3.8'

services:
  postgres:
    image: postgres:15.3-alpine3.18
    expose:
      - 5432
    ports:
      - 15432:5432
    volumes:
      - postgres_data:/data/db
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
  redis:
    image: redis:7.0.11-alpine3.18
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data/db
    tty: true

volumes:
  postgres_data:
  redis_data:
